#ifndef CONFIG_H_
#define CONFIG_H_

#define SERIAL_BAUD 115200
#define PIN_SPEAKER 8
#define PIN_SERVO_CONTROL 9
#define PIN_STRIPE_DATA 3
#define PIN_STRIPE_CLOCK 2
#define NUM_LEDS 3
#define SERVO_POS_CLOSED 7
#define SERVO_POS_OPEN 178
#define SERVO_OPEN_MILLIS 7000
#define SERVO_GREET_OPEN_MILLIS 250
#define TARGET_FREQ 100u
#define DOOR_SERVO_POS_CLOSED 8
#define DOOR_SERVO_POS_OPEN 175
#define DOOR_BOUNCE_TIME_OFFSET_MILLIS 1000

#define SENSOR_VCNL
//#define SENSOR_ADPS


#endif /* CONFIG_H_ */
